include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.gr.dart"
    - "**.mocks.dart"

linter:
  rules:

    # Best practices
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_field_initializers_in_const_classes
    - avoid_slow_async_io
    - close_sinks
    - cancel_subscriptions
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_unnecessary_containers
    - use_super_parameters
    - unnecessary_lambdas
    - unnecessary_this

    # Memory safety & leak prevention
    - avoid_print
    - avoid_catches_without_on_clauses

    # Performance
    - avoid_init_to_null
    - unnecessary_overrides
    - prefer_single_quotes
    - avoid_redundant_argument_values

    # Code style
    - always_put_required_named_parameters_first
    - sort_child_properties_last
    - avoid_setters_without_getters
    # - public_member_api_docs
    - sort_constructors_first
    - omit_local_variable_types
    - cascade_invocations
    - use_function_type_syntax_for_parameters
    - prefer_typing_uninitialized_variables


dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/recommended.yaml
    - package:dart_code_metrics_presets/flutter.yaml
    - package:dart_code_metrics_presets/performance.yaml
  metrics:
    cyclomatic-complexity: 15
    number-of-parameters: 4
    maximum-nesting-level: 4
    lines-of-executable-code: 50
    number-of-methods: 10

  rules:
    - avoid-collection-methods-with-unrelated-types
    - avoid-global-state
    - avoid-late-keyword
    - avoid-long-functions
    - avoid-long-files
    - avoid-nested-conditional-expressions
    - avoid-non-null-assertion
    - avoid-unnecessary-type-casts
    - prefer-first
    - prefer-last
    - no-equal-then-else
    - prefer-trailing-comma
    - no-boolean-literal-compare
    - no-empty-block
    - no-magic-number
    - no-equal-arguments
    - prefer-async-await
    - avoid-unnecessary-setstate
    - prefer-extracting-callbacks
    - arguments-ordering
    - member-ordering
    - avoid-stateless-widget-initialized-fields
    - prefer-conditional-expressions

  anti-patterns:
    - long-method
    - long-parameter-list
    - nesting
    - blob

  pubspec-checker:
    exclude:
      - build_runner
      - freezed
      - hive_generator
