name: poultrypal
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ^3.6.0

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.6.0
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  firebase_messaging: ^15.2.10
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.5.2
  flutter_local_notifications: ^19.4.0
  flutter_localizations:
    sdk: flutter
  google_mlkit_image_labeling: ^0.14.1
  google_mobile_ads: ^6.0.0 # this version has major problem
  # google_mobile_ads: ^5.3.1
  http: ^1.4.0
  image: ^4.5.4
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  # intl: ^0.19.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pie_menu: ^3.3.0
  tflite_flutter: ^0.11.0
  upgrader: ^11.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.6.0
  change_app_package_name: ^1.5.0
  dart_code_metrics_presets: ^2.24.0
  flutter_gen_runner: ^5.11.0

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

  assets:
    enabled: true
flutter:
  generate: true # Add this line
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/user_manual/
    - assets/models/model.tflite
    - assets/models/labels.txt
