name: poultrypal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.5.0
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  google_mlkit_image_labeling: ^0.14.1
  # google_mobile_ads: ^5.2.0
  http: ^1.4.0
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pie_menu: ^3.3.0
  tflite_flutter: ^0.11.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  flutter_gen_runner: ^5.10.0

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

  assets:
    enabled: true
flutter:
  generate: true # Add this line
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/user_manual/
    - assets/models/model.tflite
    - assets/models/labels.txt
