// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSMLvfuo8akgp5DUqRMOX_-x49GnThaQ0',
    appId: '1:110131626994:web:70a0336f3560b76b8e616b',
    messagingSenderId: '110131626994',
    projectId: 'poultry-pal-7f86c',
    authDomain: 'poultry-pal-7f86c.firebaseapp.com',
    databaseURL: 'https://poultry-pal-7f86c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poultry-pal-7f86c.appspot.com',
    measurementId: 'G-91JSE3NSYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWaJnbOKSiJFZdwZEJ0ND8iidMSBGZnYs',
    appId: '1:110131626994:android:862dc81252be6a938e616b',
    messagingSenderId: '110131626994',
    projectId: 'poultry-pal-7f86c',
    databaseURL: 'https://poultry-pal-7f86c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poultry-pal-7f86c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIs3gHPjPibu8_JPMRumXxfU3f6tDU_KA',
    appId: '1:110131626994:ios:1f203364bc5135d48e616b',
    messagingSenderId: '110131626994',
    projectId: 'poultry-pal-7f86c',
    databaseURL: 'https://poultry-pal-7f86c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poultry-pal-7f86c.appspot.com',
    iosBundleId: 'com.nevronus.poultrypal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIs3gHPjPibu8_JPMRumXxfU3f6tDU_KA',
    appId: '1:110131626994:ios:a19800c07ce1df178e616b',
    messagingSenderId: '110131626994',
    projectId: 'poultry-pal-7f86c',
    databaseURL: 'https://poultry-pal-7f86c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poultry-pal-7f86c.appspot.com',
    iosBundleId: 'com.example.poultrypal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBBCszvMJTKPZgpbMz7tAb_miKiJ9HRV8',
    appId: '1:110131626994:web:f168578ab059e6268e616b',
    messagingSenderId: '110131626994',
    projectId: 'poultry-pal-7f86c',
    authDomain: 'poultry-pal-7f86c.firebaseapp.com',
    databaseURL: 'https://poultry-pal-7f86c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poultry-pal-7f86c.appspot.com',
    measurementId: 'G-JEWRBVCJXQ',
  );
}
